src/wacca_probe/models/wacca.py
#!/usr/bin/env/ python3
# -*- coding: utf-8 -*-
"""
    :Author: yuangezhizao
    :Time: 2021/7/12 23:33
    :Site: https://www.yuangezhizao.cn
    :Copyright: © 2021 yuangezhizao <root@yuangezhizao.cn>
"""
from wacca_probe.models.common import HasId, HasTime
from wacca_probe.plugins.extensions import db


class Record(db.Model, HasId, HasTime):
    __bind_key__ = 'wacca'
    __tablename__ = 'record'

    scoreId = db.Column(db.Integer)
    modeName = db.Column(db.VARCHAR(50))
    comboCount = db.Column(db.Integer)
    # productId = db.Column(db.Integer)
    musicRate = db.Column(db.VARCHAR(50))
    gameDate = db.Column(db.DateTime, nullable=False)
    storeId = db.Column(db.Integer)
    greatCount = db.Column(db.Integer)
    # productName = db.Column(db.VARCHAR(50))
    # machineName = db.Column(db.VARCHAR(50))
    musicName = db.Column(db.VARCHAR(50))
    score = db.Column(db.Integer)
    marvelousCount = db.Column(db.Integer)
    machineId = db.Column(db.Integer)
    musicId = db.Column(db.Integer)
    goodCount = db.Column(db.Integer)
    musicGradeName = db.Column(db.VARCHAR(50))
    storeName = db.Column(db.VARCHAR(50))
    artistName = db.Column(db.VARCHAR(50))
    musicGrade = db.Column(db.Integer)
    musicImage = db.Column(db.VARCHAR(255))
    missCount = db.Column(db.Integer)

    def __init__(self, scoreId, modeName, comboCount, musicRate, gameDate, storeId, greatCount,
                 musicName, score, marvelousCount, machineId, musicId, goodCount, musicGradeName, storeName, artistName,
                 musicGrade, musicImage, missCount):
        self.scoreId = scoreId
        self.modeName = modeName
        self.comboCount = comboCount
        self.musicRate = musicRate
        self.gameDate = gameDate
        self.storeId = storeId
        self.greatCount = greatCount
        self.musicName = musicName
        self.score = score
        self.marvelousCount = marvelousCount
        self.machineId = machineId
        self.musicId = musicId
        self.goodCount = goodCount
        self.musicGradeName = musicGradeName
        self.storeName = storeName
        self.artistName = artistName
        self.musicGrade = musicGrade
        self.musicImage = musicImage
        self.missCount = missCount

    def __repr__(self):
        return '<Record (%s, %s, %s, %s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)>' % (
            self.id, self.scoreId, self.modeName, self.comboCount, self.musicRate, self.gameDate,
            self.storeId, self.greatCount, self.musicName, self.score, self.marvelousCount, self.machineId,
            self.musicId, self.goodCount, self.musicGradeName, self.storeName, self.artistName, self.musicGrade,
            self.musicImage, self.missCount)

    def to_dict(self):
        return {c.name: getattr(self, c.name, None) for c in self.__table__.columns}

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def update(self):
        db.session.commit()
        return self

src/wacca_probe/views/main.py
#!/usr/bin/env/ python3
# -*- coding: utf-8 -*-
"""
    :Author: yuangezhizao
    :Time: 2021/7/13 19:29
    :Site: https://www.yuangezhizao.cn
    :Copyright: © 2021 yuangezhizao <root@yuangezhizao.cn>
"""
import flask

from wacca_probe import cache
from wacca_probe.models.wacca import Record
from wacca_probe.plugins.extensions import db

app = flask.current_app
bp = flask.Blueprint('main', __name__)


@bp.route('/')
@cache.cached()
def site_index():
    return flask.render_template('index.html')


@bp.route('/record')
@cache.cached()
def record():
    page = int(flask.request.args.get('page', 1))
    per_page = int(flask.request.args.get('per_page', 20))
    if 'all' in flask.request.args:
        per_page = 10000

    stmt = db.select(Record).order_by(Record.id.desc())  # Note: stmt is short for 'statement'

    if 'artistName' in flask.request.args:
        _artistName = flask.request.args.get('artistName')
        stmt = stmt.filter_by(artistName=_artistName)

    record_data_paginate = db.paginate(
        stmt,
        page=page,
        per_page=per_page
    )

    # total = record_data_paginate.total
    # total_page = record_data_paginate.pages
    return flask.render_template('wacca/record/list.html', record_data_paginate=record_data_paginate,
                                 page=page, per_page=per_page)


@bp.route('/test')
def test():
    import json
    from wacca_probe.plugins.extensions import db
    from wacca_probe.models.wacca import Record

    db.create_all()

    with open('wacca_probe/static/static/json/recordList.json', encoding='utf-8') as f:
        record = f.read()
        record_json = json.loads(record)
        data = record_json['data']
        record_count = len(data)
        for i in range(record_count - 1, -1, -1):
            scoreId = data[i]['scoreId']
            modeName = data[i]['modeName']
            comboCount = data[i]['comboCount']
            # productId = data[i]['productId']
            musicRate = data[i]['musicRate']
            gameDate = data[i]['gameDate']
            storeId = data[i]['storeId']
            greatCount = data[i]['greatCount']
            # productName = data[i]['productName']
            # machineName = data[i]['machineName']
            musicName = data[i]['musicName']
            score = data[i]['score']
            marvelousCount = data[i]['marvelousCount']
            machineId = data[i]['machineId']
            musicId = data[i]['musicId']
            goodCount = data[i]['goodCount']
            musicGradeName = data[i]['musicGradeName']
            storeName = data[i]['storeName']
            artistName = data[i]['artistName']
            musicGrade = data[i]['musicGrade']
            musicImage = data[i]['musicImage']
            missCount = data[i]['missCount']
            if not Record.query.filter(Record.scoreId == scoreId).first():
                new_wacca_Record = Record(scoreId, modeName, comboCount, musicRate, gameDate, storeId, greatCount,
                                          musicName, score, marvelousCount, machineId, musicId, goodCount,
                                          musicGradeName, storeName, artistName, musicGrade, musicImage, missCount)
                r = new_wacca_Record.save()
                print(r)
            else:
                print(f'scoreId {scoreId} 已存在')
    return '1'

src/wacca_probe/templates/wacca/record/list.html
{% extends "/base.html" %}

{% from 'macros.html' import pagination_widget with context %}

{% block title %}WACCA－快速预览－{% endblock %}

{% block body %}
    <div class="ui centered grid">
        <div class="eleven wide computer column">
            <div class="ui blue pointing menu">
                <a class="active item"><i class="circle icon"></i>WACCA－快速预览－</a>
                <a class="item" href="{{ url_for('main.site_index') }}"><i class="arrow left icon"></i>返回首页</a>
            </div>

            <div class="ui dividing blue header">
                <div class="content">
                    <h2>quick_record</h2>
                </div>
            </div>

            <table id="table" class="ui compact sortable celled unstackable striped blue table">
                <thead>
                <tr class="positive">
                    <th>id</th>
                    <th>mode</th>
                    <th>musicImage</th>
                    <th class="two wide">musicName</th>
                    <th class="two wide">artistName</th>
                    <th>Grade</th>
                    <th>score</th>
                    <th>Rate</th>
                    <th>CountTable</th>
                    <th>combo</th>
                    <th>storeName</th>
                    <th>gameDate</th>
                </tr>
                </thead>
                <tbody>
                {% for data in record_data_paginate.items %}
                    <tr>
                        <td>
                            {{ data.id }}
                        </td>
                        <td>
                            {{ data.modeName }}
                        </td>
                        <td>
                            <div class="ui small image">
                                <img width="70%" src="{{ data.musicImage }}">
                            </div>
                        </td>
                        <td>
                            {{ data.musicName }}
                        </td>
                        <td>
                            {{ data.artistName }}
                        </td>
                        <td class="{% if data.musicGrade == 1 %}blue{% elif data.musicGrade == 2 %}yellow{% elif data.musicGrade == 3 %}pink{% else %}{% endif %}">
                            {{ data.musicGradeName }}
                        </td>
                        <td class="
{% if data.score == 1000000 %}
    black
{% elif data.score >= 980000 %}
    grey
{% elif data.score >= 950000 %}
    brown
{% elif data.score >= 900000 %}
    yellow
{% elif data.score >= 850000 %}
    orange
{% elif data.score >= 800000 %}
    red
{% elif data.score >= 700000 %}
    pink
{% elif data.score >= 480000 %}
    purple
{% elif data.score >= 1 %}
    violet
{% elif data.score == 0 %}
    blue
{% else %}
{% endif %}">
                            {{ data.score }}
                        </td>
                        <td class="
{% if data.score == 1000000 %}
    black
{% elif data.score >= 980000 %}
    grey
{% elif data.score >= 950000 %}
    brown
{% elif data.score >= 900000 %}
    yellow
{% elif data.score >= 850000 %}
    orange
{% elif data.score >= 800000 %}
    red
{% elif data.score >= 700000 %}
    pink
{% elif data.score >= 480000 %}
    purple
{% elif data.score >= 1 %}
    violet
{% elif data.score == 0 %}
    blue
{% else %}
{% endif %}">
                            {{ data.musicRate }}
                        </td>
                        <td class="{% if data.missCount == 0 %}brown{% else %}{% endif %}">
                            <span style="color:deeppink;font-weight:bold;">marvelous</span>：
                            {{ data.marvelousCount }}<br>

                            <span style="color:green;font-weight:bold;">great</span>：
                            <span style="{% if data.greatCount > 5 %}color:blue;
                            {% elif data.greatCount > 0 %}color:red;font-weight:bold;
                            {% else %}color:pink;
                            {% endif %}">
                                    {{ data.greatCount }}
                            </span><br>

                            <span style="color:blue;font-weight:bold;">good</span>：
                            <span style="{% if data.goodCount > 5 %}color:blue;
                            {% elif data.goodCount > 0 %}color:red;font-weight:bold;
                            {% else %}color:pink;
                            {% endif %}">
                                    {{ data.goodCount }}
                            </span><br>

                            <span style="color:gray;font-weight:bold;">miss</span>：
                            <span style="{% if data.missCount > 5 %}color:blue;
                            {% elif data.missCount > 0 %}color:red;font-weight:bold;
                            {% else %}color:pink;
                            {% endif %}">
                                    {{ data.missCount }}
                            </span>
                        </td>
                        <td class="{% if data.missCount == 0 %}brown{% else %}{% endif %}">
                            {{ data.comboCount }}
                        </td>
                        <td>
                            {{ data.storeName }}
                        </td>
                        <td data-tooltip="{{ data.gameDate }}" data-inverted="">
                            {{ data.gameDate | my_split(' ', 0) }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {{ pagination_widget(record_data_paginate, 'main.record') }}

            <div class="ui divider"></div>
            <footer>
                <div class="ui info message" style="text-align: center;">
                    yuangezhizao&nbsp&nbsp&nbsp&nbsp©&nbsp&nbsp&nbsp&nbsp2021 - 2025<br>
                    Powered by Railway
                </div>
            </footer>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/tablesorter/dist/js/jquery.tablesorter.min.js"></script>
    <script>
        $(document).ready(function () {
                $("#table").tablesorter();
            }
        );
    </script>
{% endblock %}