src/wacca_probe/views/main.py
#!/usr/bin/env/ python3
# -*- coding: utf-8 -*-
"""
    :Author: yuangezhizao
    :Time: 2021/7/13 19:29
    :Site: https://www.yuangezhizao.cn
    :Copyright: © 2021 yuangezhizao <root@yuangezhizao.cn>
"""
import flask

from wacca_probe import cache
from wacca_probe.models.wacca import Record
from wacca_probe.plugins.extensions import db

app = flask.current_app
bp = flask.Blueprint('main', __name__)


@bp.route('/')
@cache.cached()
def site_index():
    return flask.render_template('index.html')


@bp.route('/record')
@cache.cached()
def record():
    page = int(flask.request.args.get('page', 1))
    per_page = int(flask.request.args.get('per_page', 20))
    if 'all' in flask.request.args:
        per_page = 10000

    stmt = db.select(Record).order_by(Record.id.desc())  # Note: stmt is short for 'statement'

    if 'artistName' in flask.request.args:
        _artistName = flask.request.args.get('artistName')
        stmt = stmt.filter_by(artistName=_artistName)

    record_data_paginate = db.paginate(
        stmt,
        page=page,
        per_page=per_page
    )

    # total = record_data_paginate.total
    # total_page = record_data_paginate.pages
    return flask.render_template('wacca/record/list.html', record_data_paginate=record_data_paginate,
                                 page=page, per_page=per_page)


@bp.route('/test')
def test():
    import json
    from wacca_probe.plugins.extensions import db
    from wacca_probe.models.wacca import Record

    db.create_all()

    with open('wacca_probe/static/static/json/recordList.json', encoding='utf-8') as f:
        record = f.read()
        record_json = json.loads(record)
        data = record_json['data']
        record_count = len(data)
        for i in range(record_count - 1, -1, -1):
            scoreId = data[i]['scoreId']
            modeName = data[i]['modeName']
            comboCount = data[i]['comboCount']
            # productId = data[i]['productId']
            musicRate = data[i]['musicRate']
            gameDate = data[i]['gameDate']
            storeId = data[i]['storeId']
            greatCount = data[i]['greatCount']
            # productName = data[i]['productName']
            # machineName = data[i]['machineName']
            musicName = data[i]['musicName']
            score = data[i]['score']
            marvelousCount = data[i]['marvelousCount']
            machineId = data[i]['machineId']
            musicId = data[i]['musicId']
            goodCount = data[i]['goodCount']
            musicGradeName = data[i]['musicGradeName']
            storeName = data[i]['storeName']
            artistName = data[i]['artistName']
            musicGrade = data[i]['musicGrade']
            musicImage = data[i]['musicImage']
            missCount = data[i]['missCount']
            if not Record.query.filter(Record.scoreId == scoreId).first():
                new_wacca_Record = Record(scoreId, modeName, comboCount, musicRate, gameDate, storeId, greatCount,
                                          musicName, score, marvelousCount, machineId, musicId, goodCount,
                                          musicGradeName, storeName, artistName, musicGrade, musicImage, missCount)
                r = new_wacca_Record.save()
                print(r)
            else:
                print(f'scoreId {scoreId} 已存在')
    return '1'

src/wacca_probe/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="WACCA 查分器,华卡,华卡音舞,yuangezhizao"/>
    <meta name="description" content="这里是个人在用的 WACCA 查分器">
    <meta name="author" content="yuangezhizao"/>
    <meta name="Copyright" content="Copyright yuangezhizao All Rights Reserved."/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui/dist/semantic.min.css">
    <link rel="dns-prefetch" href="//wacca.yuangezhizao.cn">
    <link rel="dns-prefetch" href="//lab.yuangezhizao.cn">
    <link rel="dns-prefetch" href="//www.yuangezhizao.cn">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=yes">
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}
    <div class="ui container">
        <div class="ui blue pointing menu">
            {% block nav %}
                <a class="active item"><i class="home icon"></i>首页</a>
                <a class="item" href="https://github.com/yuangezhizao/wacca_probe" target="_blank"><i
                        class="archive icon"></i>源码</a>
            {% endblock %}
        </div>
        {% block content %}{% endblock %}
        <div class="ui divider"></div>
        <footer>
            <div class="ui info message" style="text-align: center;">
                yuangezhizao&nbsp&nbsp&nbsp&nbsp©&nbsp&nbsp&nbsp&nbsp2021 - 2025<br>
                Powered by Railway
            </div>
        </footer>
    </div>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui/dist/semantic.min.js"></script>
<script>
    $('.message .close').on('click', function () {
        $(this).closest('.message').transition('fade');
    });
    $('.selection.dropdown')
        .dropdown()
    ;
</script>
{% block script %}{% endblock %}
<script async defer data-website-id="db3e3c5c-5187-4f7a-9bc3-c281085242ee" src="https://umami.yuangezhizao.cn/mikecao.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-E170V9QX4M"></script>
<script defer src='https://hm.baidu.com/hm.js?fa663a4c914007f9c4664ea57bbd8698'></script>
<script src="https://cdn-go.cn/aegis/aegis-sdk/latest/aegis.min.js"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'G-E170V9QX4M');
    var _hmt = _hmt || [];
    const aegis = new Aegis({
        id: 'p0dDnsk3jYbYXZrWKe', // 上报 id
        uin: 'Anonymous', // 用户唯一 ID（可选）
        reportApiSpeed: true, // 接口测速
        reportAssetSpeed: true, // 静态资源测速
        spa: true // spa 应用页面跳转的时候开启 pv 计算
      });
</script>
</body>
</html>

src/wacca_probe/templates/index.html
{% extends "/base.html" %}

{% block title %}WACCA 查分器{% endblock %}

{% block content %}
    <div class="ui positive message">
        <h2 class="ui header">欢迎访问 ヽ(･ω･´ﾒ)</h2>
        <p>这里是个人在用的 WACCA 查分器
        </p>
    </div>
    <h4 class="ui top attached block purple header">
        record
    </h4>
    <div class="ui attached purple segment">
        <a href="{{ url_for('main.record') }}">记录（分页）</a>
    </div>
    <div class="ui bottom attached segment">
        <a href="{{ url_for('main.record') + '?all' }}">记录（全部）</a>
    </div>
{% endblock %}

src/wacca_probe/templates/macros.html
{% macro message_part() %}
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <div class="ui {{ messages[0][0] }} message">
                <i class="close icon"></i>
                <div class="header">
                </div>
                {{ messages[0][1] }}
            </div>
        {% endif %}
    {% endwith %}
{% endmacro %}

{% macro pagination_widget(pagination, endpoint) %}
    <div style="text-align: center;">
        <div class="ui buttons">
            {% if pagination.has_prev %}
                <a class="ui orange left icon button"
                   href="{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}">
                    <i class="angle double left icon"></i>上一页
                </a>
            {% else %}
                <div class="ui disabled orange button">上一页不可用</div>
            {% endif %}
            {% for p in pagination.iter_pages() %}
                {% if p %}
                    {% if p == pagination.page %}
                        <div class="ui black button">{{ p }}</div>
                    {% else %}
                        <a class="ui blue button" href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
                    {% endif %}
                {% else %}
                    <div class="ui blue basic button">…</div>
                {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
                <a class="ui green right icon button"
                   href="{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}">
                    下一页<i class="angle double right icon"></i>
                </a>
            {% else %}
                <div class="ui disabled green button">下一页不可用</div>
            {% endif %}
        </div>
    </div>
{% endmacro %}